# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#about"
  weight = 1
  
  [[main]]
  name = "Education&Experience"
  url = "#experience"
  weight = 2
  
  [[main]]
  name = "Honors&Awards"
  url = "#accomplishments"
  weight = 3
  
  [[main]]
  name = "Publications"
  url = "#publications"
  weight = 4
  
  
[[main]]
  name = "Presentations"
  url = "#talks"
  weight = 5
  
[[main]]
  name = "Projects"
  url = "#projects"
  weight = 6
  
[[main]]
  name = "Contacts"
  url = "#contact"
  weight = 7


[[main]]
  name = "Blog"
  url = "post/"
  weight = 8
  
#[[main]]
#  name = "Blog"
#  url = "#posts"
#  weight = 40
  
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
  name = "CV"
  url = "files/cv.html"
  weight = 9
  
  
#[[main]]
#  name = "Chinese"
#  url = "chinese/"
#  weight = 10









  
#  [[main]]
#  name = "Landing"  # Title of the link.
#  url = "landing/"  # Widget Page folder name.
#  weight = 90  # Position of the link in the navigation bar.
  
  
#[[main]]
#  name = "Courses"
#  url = "courses/"
#  weight = 100
